apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: juicefs
  labels:
    app: juicefsmeta
spec:
  replicas: 1
  selector:
    matchLabels:
      app: juicefsmeta
  template:
    metadata:
      labels:
        app: juicefsmeta
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
              claimName: mysql-pv-claim
        - name: mysql8-config
          configMap:
              name: mysql8-config
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
            - mountPath: /etc/mysql/conf.d/my.cnf
              subPath: my.cnf
              name: mysql8-config
          ports:
            - containerPort: 3306
              name: mysql
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_ROOT_HOST
              value: "%"
            - name: MYSQL_DATABASE
              value: juicefs