apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: juicefs
  labels:
    app: juicefsmeta
spec:
  replicas: 3
  selector:
    matchLabels:
      app: juicefsmeta
  template:
    metadata:
      labels:
        app: juicefsmeta
    spec:
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mysql-pv-claim
        - name: init-shell
          configMap:
              name: mysql-init-script
      containers:
        - name: mysql
          image: mysql
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - mountPath: /var/lib/mysql
              name: data
            - mountPath: /docker-entrypoint-initdb.d
              name: init-shell
              readOnly: true
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 512Mi
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "123456"
            - name: MYSQL_ROOT_HOST
              value: "%"
          command: ["mysqld"]
          args:
            - --default-authentication-plugin=mysql_native_password
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
          lifecycle:
            postStart:
              exec:
                command: [ "/bin/sh", "-c", "chown -R mysql:mysql /var/lib/mysql" ]

