apiVersion: v1
kind: Namespace
metadata:
  name: juicefs
---
apiVersion: v1
kind: Service
metadata:
  name: juicefsmeta
  namespace: juicefs
spec:
  selector:
    app: juicefsmeta
  ports:
    - protocol: TCP
      name: mysql
      port: 3306
      targetPort: 3306
  clusterIP: None