apiVersion: v1
kind: Service
metadata:
  name: juicefsmeta
  namespace: juicefs
spec:
  selector:
    app: juicefsmeta
  ports:
    - protocol: TCP
      name: mysql
      port: 3306
      targetPort: 3306
      nodePort: 30366
  type: NodePort